# Generated by Django 4.1 on 2023-09-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome do Curso')),
                ('campus', models.IntegerField(choices=[(5, 'Gurupi'), (1, 'Palmas'), (3, 'Arraias'), (2, 'Porto Nacional'), (4, 'Miracema')], verbose_name='Campus')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registor')),
                ('data_de_atualização', models.DateTimeField(auto_now=True, verbose_name='Data da última modificação')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=500, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('matricula', models.IntegerField(default=0, null=True, verbose_name='Mátricula')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Imagem do Aluno')),
                ('situacao', models.IntegerField(choices=[(2, 'Formado'), (1, 'Vinculado'), (3, 'Jubilado'), (4, 'Evadido')], verbose_name='Sitação')),
                ('forma_de_ingresso', models.IntegerField(choices=[(1, 'Vestibular'), (3, 'PSEnem'), (2, 'SISU')], verbose_name='Forma de Ingresso')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Regitro')),
                ('data_de_atualização', models.DateTimeField(auto_now=True, verbose_name='Data da Última <odificação')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gerenciamento_academico.curso', verbose_name='Curso')),
            ],
        ),
    ]
