# Generated by Django 4.1 on 2023-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Vinculado'), (4, 'Evadido'), (3, 'Jubilado'), (2, 'Formado')], verbose_name='Sitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.IntegerField(choices=[(3, 'Arraias'), (1, 'Palmas'), (4, 'Miracema'), (5, 'Gurupi'), (2, 'Porto Nacional')], verbose_name='Campus'),
        ),
    ]
