# Generated by Django 4.1 on 2023-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0006_alter_aluno_forma_de_ingresso_alter_aluno_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_de_ingresso',
            field=models.IntegerField(choices=[(2, 'SISU'), (3, 'PSEnem'), (1, 'Vestibular')], verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(2, 'Formado'), (3, 'Jubilado'), (1, 'Vinculado'), (4, 'Evadido')], verbose_name='Sitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.IntegerField(choices=[(5, 'Gurupi'), (2, 'Porto Nacional'), (4, 'Miracema'), (3, 'Arraias'), (1, 'Palmas')], verbose_name='Campus'),
        ),
    ]
