# Generated by Django 4.1 on 2023-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0008_alter_aluno_situacao_alter_curso_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_de_ingresso',
            field=models.IntegerField(choices=[(2, 'SISU'), (1, 'Vestibular'), (3, 'PSEnem')], verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(2, 'Formado'), (4, 'Evadido'), (3, 'Jubilado'), (1, 'Vinculado')], verbose_name='Sitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.IntegerField(choices=[(3, 'Arraias'), (1, 'Palmas'), (5, 'Gurupi'), (2, 'Porto Nacional'), (4, 'Miracema')], verbose_name='Campus'),
        ),
    ]
