# Generated by Django 4.1 on 2023-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0010_alter_aluno_forma_de_ingresso_alter_aluno_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_de_ingresso',
            field=models.IntegerField(choices=[(1, 'Vestibular'), (2, 'SISU'), (3, 'PSEnem')], verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(3, 'Jubilado'), (4, 'Evadido'), (1, 'Vinculado'), (2, 'Formado')], verbose_name='Sitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.IntegerField(choices=[(4, 'Miracema'), (5, 'Gurupi'), (1, 'Palmas'), (3, 'Arraias'), (2, 'Porto Nacional')], verbose_name='Campus'),
        ),
    ]
