# Generated by Django 4.1 on 2023-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0014_alter_aluno_situacao_alter_curso_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(2, 'Formado'), (1, 'Vinculado'), (3, 'Jubilado'), (4, 'Evadido')], verbose_name='Sitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.IntegerField(choices=[(4, 'Miracema'), (2, 'Porto Nacional'), (3, 'Arraias'), (5, 'Gurupi'), (1, 'Palmas')], verbose_name='Campus'),
        ),
    ]
