# Generated by Django 4.1 on 2023-09-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0015_alter_aluno_situacao_alter_curso_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(3, 'Jubilado'), (1, 'Vinculado'), (4, 'Evadido'), (2, 'Formado')], verbose_name='Sitação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='campus',
            field=models.IntegerField(choices=[(4, 'Miracema'), (1, 'Palmas'), (5, 'Gurupi'), (3, 'Arraias'), (2, 'Porto Nacional')], verbose_name='Campus'),
        ),
    ]
