# Generated by Django 4.1 on 2023-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_academico', '0018_alter_aluno_forma_de_ingresso_alter_aluno_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='vinculo',
            field=models.IntegerField(choices=[(2, 'Inativo'), (1, 'Ativo')], default=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='forma_de_ingresso',
            field=models.IntegerField(choices=[(2, 'SISU'), (1, 'Vestibular'), (3, 'PSEnem')], verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Vinculado'), (2, 'Formado'), (3, 'Jubilado'), (4, 'Evadido')], default=1, verbose_name='Sitação'),
        ),
    ]
